### ISSUE TITLE
Suggestion: Add an option to filer out Northeast Regional owl trains

### ISSUE THREAD

**Issue by ghost** [tikkisean/rail-for-less#3]
Although I appreciate how much cheaper the overnight owl trains are along the northeast corridor, the overnight layover in New York, at a time when establishments in Penn Station would be closed (and I'd rather be sleeping comfortably) is a deal breaker for me.

If it's at all possible, I would love it if you guys added an option to filter those specific trains out, leaving only regular northeast regional trains with a ~7 hour run time left over.

Appreciate the work you guys do!

**Comment by tikkisean** [comment]
With the latest update you can now filter by duration and times to remove Night Owl fares.
